# Generated by Django 5.0.6 on 2024-06-11 01:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pong.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intra_name', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150, unique=True)),
                ('avatar', models.FileField(blank=True, default='/static/pong/img/default_avatar.svg', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg']), pong.models.file_size_validator])),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', pong.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('opponent_display_name', models.CharField(max_length=150)),
                ('opponent_score', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_is_friendly', models.BooleanField(default=True)),
                ('user2_is_friendly', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_relationship'),
        ),
    ]
